// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use local Supabase URL for development
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "http://127.0.0.1:54321";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0";

// IMPORTANT: set default schema here. If your table lives in 'app', set VITE_DB_SCHEMA=app
const DEFAULT_SCHEMA = (import.meta as any)?.env?.VITE_DB_SCHEMA || 'public';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'sb-main-auth-token', // Use a specific storage key
    debug: false // Disable debug logging to reduce noise
  },
  db: {
    schema: DEFAULT_SCHEMA,
  },
  // Enable realtime for the main client
  realtime: {
    enabled: true
  }
});
