name: Build and Deploy Sproutify Classrooms
on:
  push:
    branches: [main]         # prod only
  workflow_dispatch: {}       # allow manual runs
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
      VITE_STRIPE_PUBLISHABLE_KEY: ${{ secrets.VITE_STRIPE_PUBLISHABLE_KEY }}
      VITE_DB_SCHEMA: ${{ secrets.VITE_DB_SCHEMA }}
      # (Feature flags: set defaults in code; avoid referencing missing vars/secrets here.)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Build
        shell: bash
        run: |
          set -euo pipefail
          npm run build
          echo "commit=${GITHUB_SHA}" > dist/build-info.txt
          date -u +"built_utc=%Y-%m-%dT%H:%M:%SZ" >> dist/build-info.txt
          printf '%s\n' \
            '<!doctype html>' \
            '<meta charset="utf-8">' \
            '<title>Build Info</title>' \
            '<pre id="info"></pre>' \
            '<script>' \
            "document.getElementById('info').textContent =" \
            "  'commit=${GITHUB_SHA}\\n' +" \
            "  'built_utc=$(date -u +%Y-%m-%dT%H:%M:%SZ)';" \
            '</script>' \
            > dist/build-info.html
          printf '%s\n' \
            '# Never cache the SPA entry so new bundles get picked up immediately' \
            '<IfModule mod_headers.c>' \
            '  <Files "index.html">' \
            '    Header set Cache-Control "no-cache, no-store, must-revalidate"' \
            '    Header set Pragma "no-cache"' \
            '    Header set Expires 0' \
            '  </Files>' \
            '</IfModule>' \
            '' \
            '# SPA routing that still serves real files directly' \
            '<IfModule mod_rewrite.c>' \
            '  RewriteEngine On' \
            '  RewriteBase /' \
            '' \
            '  # If it'\''s an existing file or directory, serve it as-is' \
            '  RewriteCond %{REQUEST_FILENAME} -f [OR]' \
            '  RewriteCond %{REQUEST_FILENAME} -d' \
            '  RewriteRule ^ - [L]' \
            '' \
            '  # Otherwise, fall back to the SPA entry' \
            '  RewriteRule . /index.html [L]' \
            '</IfModule>' \
            > dist/.htaccess
      - name: Deploy via rsync over SSH
        uses: easingthemes/ssh-deploy@v5.0.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.IONOS_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.IONOS_HOST }}
          REMOTE_USER: ${{ secrets.IONOS_USERNAME }}
          TARGET: ${{ secrets.IONOS_SCHOOL_PATH }}
          SOURCE: dist/
          ARGS: "-avz --delete --human-readable --progress --exclude='.well-known/*'"
          SSH_CMD_ARGS: "-p 2222"
          SCRIPT_AFTER: |
            set -e
            cd "${{ secrets.IONOS_SCHOOL_PATH }}"
            echo "PWD: $(pwd)"
            ls -la | sed -n '1,160p'
            echo "---- build-info.txt ----"
            [ -f build-info.txt ] && cat build-info.txt || echo "missing"
            echo "---- build-info.html (first 10 lines) ----"
            [ -f build-info.html ] && head -n 10 build-info.html || echo "missing"
