name: Build and Deploy Sproutify Classrooms

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Deploy with rsync
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.IONOS_HOST }}
          username: ${{ secrets.IONOS_USERNAME }}
          password: ${{ secrets.IONOS_PASSWORD }}
          script: |
            echo "-----> Deploying to Live Server..."
            # This is now correct because httpdocs is a dedicated public folder
            rsync -avz --delete ./dist/ ${{ secrets.IONOS_SCHOOL_PATH }}
            echo "-----> Deployment complete."